services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    env_file: .env
    networks:
      - incep-network
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
  wordpress:
    container_name: wordpress
    image: wordpress
    build: requirements/wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - incep-network
    depends_on:
      - mariadb
    restart: always
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/ngnix
    env_file: .env
    ports:
      - target: 443
        published: 443
    networks:
      - incep-network
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: always

networks:
  incep-network:
    name: incep-network
    driver: bridge
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o : bind
      device: /home/ahamou/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ahamou/data/mariadb

